apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskit
  template:
    metadata:
      labels:
        app: taskit
    spec:
      containers:
        - name: taskit
          image: pannkakor/taskit-backend:1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: taskit-config
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskit-session-secret
                  key: SESSION_SECRET
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/just-task-it
      volumes:
        - name: log-volume
          emptyDir: {}