apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskit
  template:
    metadata:
      labels:
        app: taskit
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: taskit
          image: registry.gitlab.lnu.se/eg223ps/assignment-2-2dv013/taskit-backend:main
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: taskit-config
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskit-session-secret
                  key: SESSION_SECRET
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/just-task-it
      volumes:
        - name: log-volume
          emptyDir: {}