apiVersion: v1
kind: Service
metadata:
  name: taskit
  labels:
    app: taskit
spec:
  type: NodePort
  selector:
    app: taskit
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30908