apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
data:
  PORT: "4000"
  ANALYTICS_DB_URL: "mongodb://mongodb:27019/just-task-it-analytics"
  RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672"